env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    TOKEN: "ENCRYPTED[9aaf5d478b7ed755a49ec6f9307c22a3cc571118818fb7f4152931262f0705d7818e0ab378e044ec3f23ca9ea0955e86]"
    EMAIL: "ENCRYPTED[3bbee728d0fdd7bb88c7fd907e3e28fc5d73ebc68d73ab8b7aa9e13d5697195f4fed2feb667c845357a063887c2925c2]"
    UNAME: "ENCRYPTED[9ef2cd60d778d03e947a740930e0c5093e08a965d7568382447fa2cc5ec9ed47e4543669a3ad0b25061506f22c45fc55]"
    TLGTK: "ENCRYPTED[213e32fa8322b178aa2767dc48a37d3a71f87742c45f14ba09d9799b615a6a3857e8e219c30dc7cfb566b0aecf427a98]"

task:
  name: master
  timeout_in: 2h
  container:
    image: dopaemon/bionic:latest
    cpu: 4
    memory: 8G

  packages_script:
    - rm -rf *
    - sudo apt update
    - sudo apt-get install -y python3 curl zip wget ccache rclone git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev pigz
  github_script:
    - git config --global user.name "$UNAME"
    - git config --global user.email "$EMAIL"
  cfolder_script:
    - mkdir -p /tmp/ci/Kernel
    - mkdir -p /tmp/ci/Kernel/Upload
  clone_script:
    - cd /tmp/ci/Kernel
    - git clone -b master --single-branch https://github.com/KernelPanic-OpenSource/android_kernel_xiaomi_sweet.git /tmp/ci/Kernel/Source
    - git clone -b master --single-branch --depth="1" https://github.com/kdrag0n/proton-clang.git /tmp/ci/Kernel/clang
  export_script:
    - touch ~/.kernel
    - echo "export NAME="Doraemon-Kernel-$(date +"%d%m%Y")"" >> ~/.kernel
    - echo "export TIME="$(date +"%d%m%Y")"" >> ~/.kernel
    - echo "export CC=clang" >> ~/.kernel
    - echo "export ARCH=arm64" >> ~/.kernel
    - echo "export SUBARCH=arm64" >> ~/.kernel
    - echo "export DTC_EXT=dtc"
    - echo "export CROSS_COMPILE=aarch64-linux-gnu-" >> ~/.kernel
    - echo "export CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> ~/.kernel
    - echo "export PATH="/tmp/ci/Kernel/clang/bin:${PATH}"" >> ~/.kernel

  aosp_kernel_script:
    - source ~/.kernel
    - cd /tmp/ci/Kernel/Source
    - export D='"'
    - echo CONFIG_LOCALVERSION="$D"-"$NAME"-AOSP"$D" >> arch/arm64/configs/vendor/sweet_user_defconfig
  aosp_compile_script:
    - source ~/.kernel
    - cd /tmp/ci/Kernel/Source
    - make O=out sweet_user_defconfig
    - make -j$(nproc --all) O=out ARCH=arm64 CC="ccache clang" CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- |& tee ~/$TIME.txt
  aosp_dtbo_script:
    - cd /tmp/ci/Kernel/Source/out/arch/arm64/boot/
    - curl https://android.googlesource.com/platform/external/avb/+/refs/heads/master/avbtool.py?format=TEXT | base64 --decode > avbtool.py
    - chmod +x avbtool.py
    - python3 avbtool.py add_hash_footer --image dtbo.img --partition_size=33554432 --partition_name dtbo
  aosp_flashable_script:
    - source ~/.kernel
    - mkdir -p /tmp/ci/flashable
    - cd /tmp/ci/flashable
    - git clone -b sweet --depth="1" https://github.com/KernelPanic-OpenSource/AnyKernel3.git zip
    - cp -r /tmp/ci/Kernel/Source/out/arch/arm64/boot/Image.gz /tmp/ci/flashable/zip/
    - cp -r /tmp/ci/Kernel/Source/out/arch/arm64/boot/dtbo.img /tmp/ci/flashable/zip/
    - cd zip
    - zip -rv9 "$NAME"-AOSP.zip *
  aosp_zipSigner_script:
    - source ~/.kernel
    - cd /tmp/ci/flashable/zip/
    - curl -sLo zipsigner-4.0.jar https://github.com/baalajimaestro/AnyKernel3/raw/master/zipsigner-4.0.jar
    - java -jar zipsigner-4.0.jar "$NAME"-AOSP.zip "$NAME"-AOSP-signed.zip
    - echo "export AOSP_ZIP_NAME=$NAME-AOSP-signed.zip" >> ~/.kernel
    - mv *.zip /tmp/ci/Kernel/Upload/

  clear_script:
    - rm -rf /tmp/ci/flashable/zip
    - rm -rf /tmp/ci/Kernel/Source/out

  miui_kernel_script:
    - source ~/.kernel
    - cd /tmp/ci/Kernel/Source
    - export D='"'
    - echo CONFIG_LOCALVERSION="$D"-"$NAME"-Miui"$D" >> arch/arm64/configs/vendor/sweet_user_defconfig
    - git revert 2a6823fcb33f530267b31bd4aa714a66c48b4c6d --no-commit
  miui_compile_script:
    - source ~/.kernel
    - cd /tmp/ci/Kernel/Source
    - make O=out sweet_user_defconfig
    - make -j$(nproc --all) O=out ARCH=arm64 CC="ccache clang" CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- |& tee ~/$TIME.txt
  miui_dtbo_script:
    - cd /tmp/ci/Kernel/Source/out/arch/arm64/boot/
    - curl https://android.googlesource.com/platform/external/avb/+/refs/heads/master/avbtool.py?format=TEXT | base64 --decode > avbtool.py
    - chmod +x avbtool.py
    - python3 avbtool.py add_hash_footer --image dtbo.img --partition_size=33554432 --partition_name dtbo
  miui_flashable_script:
    - source ~/.kernel
    - mkdir -p /tmp/ci/flashable
    - cd /tmp/ci/flashable
    - git clone -b sweet --depth="1" https://github.com/KernelPanic-OpenSource/AnyKernel3.git zip
    - cp -r /tmp/ci/Kernel/Source/out/arch/arm64/boot/Image.gz /tmp/ci/flashable/zip/
    - cp -r /tmp/ci/Kernel/Source/out/arch/arm64/boot/dtbo.img /tmp/ci/flashable/zip/
    - cd zip
    - zip -rv9 "$NAME"-MIUI.zip *
  miui_zipSigner_script:
    - source ~/.kernel
    - cd /tmp/ci/flashable/zip/
    - curl -sLo zipsigner-4.0.jar https://github.com/baalajimaestro/AnyKernel3/raw/master/zipsigner-4.0.jar
    - java -jar zipsigner-4.0.jar "$NAME"-MIUI.zip "$NAME"-MIUI-signed.zip
    - echo "export MIUI_ZIP_NAME=$NAME-MIUI-signed.zip" >> ~/.kernel
    - mv *.zip /tmp/ci/Kernel/Upload/

  telegram_script:
    - source ~/.kernel
    - curl -F document=@"/tmp/ci/Kernel/Upload/$AOSP_ZIP_NAME" https://api.telegram.org/bot$TLGTK/sendDocument?chat_id=@KernelPanic_OpenSource_CI
    - curl -F document=@"/tmp/ci/Kernel/Upload/$MIUI_ZIP_NAME" https://api.telegram.org/bot$TLGTK/sendDocument?chat_id=@KernelPanic_OpenSource_CI
    - curl https://api.telegram.org/bot$TLGTK/sendMessage?chat_id=@KernelPanic_OpenSource_CI&text=Done
  checkout_script:
    - ls /tmp/ci/Kernel/Source/out/arch/arm64/boot/
    - ls /tmp/ci/flashable/zip/
